### ISSUE TITLE
Support cython 3

### ISSUE THREAD

**Issue by gonzalocasas** [hagberg/planarity#14]
I am maintaining the conda-forge package of `planarity`, and currently the support for Python 3.12 is blocked because the builds are failing on Mac OS. I'm not entire sure why though, but it might be that `planarity` needs to be updated to support cython 3, according to one of the people in the migrations team: https://github.com/conda-forge/python-planarity-feedstock/pull/12

I'm not sure if it's realistic to expect this to happen, or if we should mark the package as unsupported.

**Comment by hagberg** [comment]
Works with cython 3.  Release planarity-0.5.
