### ISSUE TITLE
Planary build fails under Linux and windows

### ISSUE THREAD

**Issue by Guillem-db** [hagberg/planarity#7]
The last version of planarity fails both under Linux and windows when building. My package depends on planarity, so it would be really nice to know if this is easy to fix. 

 Error compiling Cython file:
------------------------------------------------------------
...
#!python
#cython: embedsignature=True
"""
Wrapper for Boyer's (C) planarity algorithms.
"""
cimport cplanarity
^
------------------------------------------------------------

planarity\planarity.pyx:6:8: 'cplanarity.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
"""
cimport cplanarity
import warnings

cdef class PGraph:
cdef cplanarity.graphP theGraph
^
------------------------------------------------------------

planarity\planarity.pyx:10:9: 'graphP' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
raise RuntimeError("planarity: Unknown error.")

def nodes(self,data=False):
DRAWPLANAR_ID=1
cdef cplanarity.DrawPlanarContext *context
^
------------------------------------------------------------

planarity\planarity.pyx:102:13: 'DrawPlanarContext' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
return nodes

def edges(self,data=False):
DRAWPLANAR_ID=1
cdef cplanarity.DrawPlanarContext *context
^
------------------------------------------------------------

planarity\planarity.pyx:126:13: 'DrawPlanarContext' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
def nodes(self,data=False):
DRAWPLANAR_ID=1
cdef cplanarity.DrawPlanarContext *context
drawing=cplanarity.gp_FindExtension(self.theGraph,
DRAWPLANAR_ID,
<void *> &context)
^
------------------------------------------------------------

planarity\planarity.pyx:105:44: Cannot convert 'void *' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
def edges(self,data=False):
DRAWPLANAR_ID=1
cdef cplanarity.DrawPlanarContext *context
drawing=cplanarity.gp_FindExtension(self.theGraph,
DRAWPLANAR_ID,
<void *> &context)
^
------------------------------------------------------------

planarity\planarity.pyx:129:44: Cannot convert 'void *' to Python object
building 'planarity.planarity' extension
error: Unable to find vcvarsall.bat

----------------------------------------
Command "C:\Users\Biel\Anaconda2\envs\py35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Biel\\AppData\\Local\\Temp\\pip-build-fo8hsahc\\planarity\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Biel\AppData\Local\Temp\pip-lvariyyb-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Biel\AppData\Local\Temp\pip-build-fo8hsahc\planarity\

[py35] C:\Users\Biel>

**Comment by hagberg** [comment]
Well, I see there are a bunch of missing files from the pypi package (e.g. cplanarity.pxd and all the .h files).  Let me try to fix that.  

Meantime could you verify you can build the version at github? https://github.com/hagberg/planarity/archive/master.zip
That one has all of the files.

**Comment by Guillem-db** [comment]
I am on it!

**Comment by Guillem-db** [comment]
Yes, it builds correctly, at least on a linux system.

**Comment by hagberg** [comment]
OK, thanks.  This is a packaging issue which I will fix with a planarity-0.4.1 release.

**Comment by hagberg** [comment]
I think I have fixed this in 968883db9680f99755186fab0f8ad8a7069db189.

Try the new planarity-0.4.1 package at https://pypi.python.org/pypi/planarity

**Comment by Guillem-db** [comment]
Solved, the upgrade works perfectly. I will add again planarity as a dependency for my framework :)

**Comment by hagberg** [comment]
Thanks a lot for this report and helping with testing to get it right.
